### ISSUE TITLE
Didn't zero the gradient in the optimizer

### ISSUE THREAD

**Issue by zeyuyun1** [alisiahkoohi/Langevin-dynamics#1]
Hi,

Thank you so much for the repository. I am learning MCMC. It's really helpful for me.
I have a question. In [class LangevinDynamics(object):](https://github.com/alisiahkoohi/Langevin-dynamics/blob/e0bd2957464ebf1ddb2f7282d65fcdcae8ce12b4/langevin_sampling/samplers.py#L5), you never run `self.optim.zero_grad()`. Is this on purpose?

You use the preconditioned SGD in gaussian_LD.py demo. However, if you change pSGLD to SGLD, it actually doesn't work:
![image](https://user-images.githubusercontent.com/43428393/140633637-a94d5e3f-8d80-462d-a42c-aa451189b62f.png)

**Comment by alisiahkoohi** [comment]
Hi,

I use `torch.autograd.grad` for gradient computation, which does not require zeroing out the gradients as it returns the gradient. This is different from `.backward()`, which accumulates the gradient in the `.grad` attribute of the tensors.

Since pSGLD is a preconditioned approach, it allows for using larger stepsizes. I am guessing you would need to reduce the the stepsize while using SGLD.

**Comment by alisiahkoohi** [comment]
Good catch! I will update it. Thank you!

**Comment by alisiahkoohi** [comment]
Closing this now. Please reopen if necessary.
